apiVersion: apps/v1
kind: Deployment
metadata:
  name: netview-deploy
  namespace: netview
  labels:
    environment: intern
    app: netview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netview
  template:
    metadata:
      labels:
        app: netview
    spec:
      volumes:
        - name: vol
          nfs:
            server: NFS-Server #TODO
            path: /mnt/data/netview
      containers:
        - name: netview
          image: crisu1710/netview
          ports:
            - containerPort: 5000
              name: web
          env:
            - name: VUE_APP_API_URL
              value: "api.home"
        - name: netview-server
          image: crisu1710/netview-server
          volumeMounts:
            - name: vol
              mountPath: /api/conf
          ports:
            - containerPort: 8090
              name: web